name: Deploy Matteo's portfolio website

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install linux dependencies
        run: sudo apt install -y zlib1g-dev libjpeg8-dev

      - name: Generate content
        run: make prod

      - name: Copy CNAME
        run: cp CNAME ./prod/

      - name: Publish current workdir to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: prod
          target-branch: gh-pages